# Supabase configuration
# Project URL: https://kkmyokfipaavjmlebjgq.supabase.co
# project_id = "kkmyokfipaavjmlebjgq"

[api]
# Port to use for the local Supabase API server
port = 54321

[db]
# Port to use for the local database server
port = 54322

[studio]
# Port to use for Supabase Studio
port = 54323

[inbucket]
# Port to use for the local email testing server
port = 54324

[auth]
# The base URL of your website — used for redirects
site_url = "http://localhost:3000"
